### ISSUE TITLE
Running bcms install for existing project causes undefined method `versioned_class=' for Version(Table doesn't exist):Class (NoMethodError)

### ISSUE THREAD

**Issue by staelen** [browsermedia/browsercms#613]
Hi, I've been trying to add browsercms into an existing project but I wasn't able to after running `bcms install`. It gave the following exception and I'm clueless as how to go about resolving it... Appreciate any help or suggestions, thanks!

/Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.13/lib/active_record/dynamic_matchers.rb:55:in `method_missing': undefined method`versioned_class=' for Version(Table doesn't exist):Class (NoMethodError)
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/browsercms-3.5.7/lib/cms/behaviors/versioning.rb:114:in `is_versioned'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/browsercms-3.5.7/app/models/cms/attachment.rb:33:in`class:Attachment'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/browsercms-3.5.7/app/models/cms/attachment.rb:2:in `<module:Cms>'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/browsercms-3.5.7/app/models/cms/attachment.rb:1:in`<top (required)>'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:469:in `load'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:469:in`block in load_file'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:639:in `new_constants_in'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:468:in`load_file'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:353:in `require_or_load'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:502:in`load_missing_constant'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:192:in `block in const_missing'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in`each'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in `const_missing'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:514:in`load_missing_constant'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:192:in `block in const_missing'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in`each'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in `const_missing'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/browsercms-3.5.7/lib/cms/attachments/configuration.rb:30:in`configure'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/browsercms-3.5.7/lib/cms/engine.rb:41:in `block in <class:Engine>'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:429:in`_run__2547266122931452847__prepare__1306960818236119409__callbacks'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in`_run_prepare_callbacks'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:74:in`prepare!'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application/finisher.rb:47:in`block in module:Finisher'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:30:in`run'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:54:in`each'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application.rb:136:in`initialize!'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/staelen/Dropbox/Work/source/research_portal/config/environment.rb:5:in`<top (required)>'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`block in require'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
    from /Users/staelen/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands.rb:25:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by jorgedavila25** [comment]
hi, I'm having the same issue. did anyone figure this out?
